### ISSUE TITLE
License

### ISSUE THREAD

**Issue by joergmschulz** [joergmschulz/docker-dovecot#3]
add proper license (MIT). Mention GPL for exim parts (Makefile) and others.

**Comment by anekar** [comment]
Is your project open source or you want to do something else ?

**Comment by joergmschulz** [comment]
It shall be open source. My part should be MIT licensed. What I need help with is: some things are GPLed (like the exim makefile); this must be marked accordingly.

**Comment by anekar** [comment]
I think when you choose a license for your project you cannot include a second. I'm not sure though.
For better information 
**[Click here](choosealicense.com)** 
or
open up an issue about your problem in their homepage on github
 **[here](https://github.com/github/choosealicense.com)**

**Comment by joergmschulz** [comment]
I'm pretty sure a project like the current one can have multi-licensing if all licenses are provided, especially MIT and GPLv3. We just have to be clear about what is licensed how - especially for the GPL part when MIT should be default.  (https://stackoverflow.com/questions/3902754/mit-vs-gpl-license). It seems most practical though to declare the whole project as GPL; this is even possible when MIT licensed code is included. The other way round, it wouldn't work out as MIT does not require the code to be redistributed along with the project while GPL does. 

Does it matter here? No - all code is available. Yes - those who take portions must be safe.

**Comment by joergmschulz** [comment]
added GPL license. So all MIT content is better protected, and the GPL parts are sufficiently cared for.
